import { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import React from 'react'
import Header from '../../../components/layout/Header'
import Layout from '../../../components/layout/Layout'

const EventAddComponent = dynamic(
    import('../../../components/liff/event/add'), {ssr: false}
)

const add: NextPage = () => {
    return (
        <> 
            <Head>
                <title>ラクメシ｜イベント作成</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header title='イベントを作成する'/>
            <Layout>
                <EventAddComponent />
            </Layout>
        </>
    )
}

export default add
