import dynamic from 'next/dynamic'
import Head from 'next/head'
import React from 'react'
import Header from '../../../components/layout/Header'
import Layout from '../../../components/layout/Layout'
import Spacer5 from '../../../components/layout/Spacer5'

const InvitationComponent = dynamic(
    import('../../../components/liff/event/invitation'), {ssr: false}
)

const invitation = () => {
    return (
        <div>
            <Head>
                <title>ラクメシ｜イベント招待状</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header title='イベント招待状'/>
            <div className='h-screen bg-yellow-100 bg-opacity-50 pt-5'>
            <Layout>
                <InvitationComponent />
            </Layout>
            </div>

        </div>
    )
}

export default invitation
