# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - rakumeshi-line

on:
  push:
    branches:
      - line
  workflow_dispatch:

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  WORKING_DIRECTORY: './line'         # set this to the path to your path of working directory inside github repository, defaults to the repository root
  PYTHON_VERSION: '3.8' 
  STARTUP_COMMAND: ''  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    # checkout the repo 
    - uses: actions/checkout@v2
    # setup python
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    # install dependencies
    - name: python install
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        sudo apt install python${{ env.PYTHON_VERSION }}-venv
        python -m venv --copies antenv
        source antenv/bin/activate
        pip install setuptools
        pip install -r requirements.txt
    # Azure login
    # - uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS_GITHUB_SECRET }}
    - uses: azure/appservice-settings@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        mask-inputs: false
        general-settings-json: '{"linuxFxVersion": "PYTHON|${{ env.PYTHON_VERSION }}"}' #'General configuration settings as Key Value pairs'
    # deploy web app
    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.WORKING_DIRECTORY }}
        startup-command: ${{ env.STARTUP_COMMAND }}
    # Azure logout
    # - name: logout
    #   run: |
    #     az logout